### PR TITLE
do not update settings if none were received (likely because a reques…

### LINKED ISSUE #27: Uncaught TypeError: Cannot read property 'flagname' of undefined
The error has this stack trace:

```
TypeError: Cannot read property 'flagname' of undefined
at Object.u [as modifications] (/vendor/ldclient-js/ldclient.min.js:1:4074)
at f (/vendor/ldclient-js/ldclient.min.js:1:1443)
at /vendor/ldclient-js/ldclient.min.js:1:1412
at /vendor/ldclient-js/ldclient.min.js:11:22303
at XMLHttpRequest.<anonymous> (/vendor/ldclient-js/ldclient.min.js:11:22056)
```

I tracked it down, it looks like this happens because `modifications` gets called with an undefined `newObj`, which happens when `updateSettings()` gets called with an undefined `settings` parameter, which happens when `requestor.fetchFlagSettings` tries to get settings but the response code is not `200` or the response does not have a `Content-type` of `application/json` due to how `fetchJSON` handles those cases. Unfortunately I do not know what the faulty response was in this case as the error was recorded using an error-tracking service.

### PR DESCRIPTION
**Pull request by apucacao**
…t error occured)

We should always check `settings` here.

Fixes #27 .

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -133,9 +133,14 @@ function connectStream() {
...
 function updateSettings(settings) {
-  var changes = utils.modifications(flags, settings);
-  var keys = Object.keys(changes);
+  var changes;
+  var keys;
   
+  if (!settings) { return; }
+
+  utils.modifications(flags, settings);
+  Object.keys(changes);
```
Comment (jkodumal) [inline src/index.js]: Shouldn't there be an assignment here?

**Comment by jkodumal** [comment]
👍
